### ISSUE TITLE
safeCoerce: Blacklisting vs Whitelisting

### ISSUE THREAD

**Issue by andywer** [amilajack/babel-plugin-fail-explicit#7]
Not 100% sure what the code's intention is, but I think you want to apply it only to operations like +, -, *, ..., but not apply it to comparisons.

I would definitely rather whitelist the supported operators than blacklisting the unsupported ones, since there is a real chance you miss something or tomorrow someone adds a new operator that breaks stuff.

Consider '<', for instance. It's also a comparison, but maybe I missed your intention here 😉

**Comment by amilajack** [comment]
Ahh so for example,
```js
'b' > 'aaa' // true
```

**Comment by andywer** [comment]
Yeah, the `path.replaceWith()` adding the `safeCoerce` check would be invoked for `'b' > 'aaa'` as well. That would probably crash the program, right?
